#!/usr/bin/env python3
"""Generate conservative TH09 progress directly from the ledgers."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
OUTPUT = ROOT / "docs" / "PROGRESS.md"
SVG = ROOT / "resources" / "progress.svg"
INITIAL_INVENTORY_EVIDENCE = {"", "ida-1.50a-initial-inventory"}


def rows(name: str) -> list[dict[str, str]]:
    with (CONFIG / name).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def measures() -> dict[str, int]:
    functions = rows("functions.csv")
    origins = {row["address"]: row for row in rows("function-origins.csv")}
    matches = rows("matches.csv")
    implemented = []
    with (CONFIG / "implemented.csv").open(newline="", encoding="utf-8") as stream:
        implemented = [row[0] for row in csv.reader(stream) if row and row[0]]
    authored = [row for row in functions if origins[row["address"]]["disposition"] == "authored"]
    source_present = [row for row in authored if row.get("source_file")]
    exact_addresses = {row["address"] for row in matches}
    source_nonexact = [row for row in source_present if row["address"] not in exact_addresses]
    without_source = [row for row in authored if not row.get("source_file")]
    excluded = [row for row in functions if origins[row["address"]]["disposition"] == "exclude"]
    unresolved = [
        row
        for row in functions
        if origins[row["address"]]["disposition"] == "review"
        and origins[row["address"]]["evidence_id"] not in INITIAL_INVENTORY_EVIDENCE
    ]
    exact_bytes = sum(int(row["size"], 0) for row in matches)
    authored_bytes = sum(int(row["size"], 0) for row in authored)
    reviewed = len(authored) + len(excluded) + len(unresolved)
    return {
        "functions": len(functions),
        "reviewed": reviewed,
        "pending": len(functions) - reviewed,
        "unresolved": len(unresolved),
        "authored": len(authored),
        "authored_bytes": authored_bytes,
        "excluded": len(excluded),
        "implemented": len(implemented),
        "source_present_bytes": sum(int(row["size"], 0) for row in source_present),
        "source_nonexact": len(source_nonexact),
        "source_nonexact_bytes": sum(int(row["size"], 0) for row in source_nonexact),
        "without_source": len(without_source),
        "without_source_bytes": sum(int(row["size"], 0) for row in without_source),
        "matches": len(matches),
        "exact_bytes": exact_bytes,
    }


def render_markdown(values: dict[str, int]) -> str:
    return f"""# TH09 reconstruction progress

Generated by `python3 scripts/progress.py`. IDA candidates are provisional;
their boundaries and origins must be reviewed independently.

| Measure | Count |
| --- | ---: |
| Tracked 1.50a function candidates | {values['functions']:,} |
| Origin/boundary review pending | {values['pending']:,} |
| Reviewed but origin-unresolved | {values['unresolved']:,} |
| Confirmed authored functions | {values['authored']:,} |
| Confirmed authored code bytes | {values['authored_bytes']:,} |
| Classified exclusions | {values['excluded']:,} |
| Source-present authored mappings | {values['implemented']:,} |
| Source-present authored bytes | {values['source_present_bytes']:,} |
| Source-present but non-exact functions | {values['source_nonexact']:,} |
| Source-present but non-exact bytes | {values['source_nonexact_bytes']:,} |
| Authored functions without maintained source | {values['without_source']:,} |
| Authored bytes without maintained source | {values['without_source_bytes']:,} |
| Canonical exact functions | {values['matches']:,} |
| Canonical exact authored bytes | {values['exact_bytes']:,} |

While review remains pending or origins remain unresolved, the authored exact
denominator is unknown. A mapped name, maintained source, successful
compilation, or IDA similarity does not contribute to the exact totals.
"""


def render_svg(values: dict[str, int]) -> str:
    total, reviewed = values["functions"], values["reviewed"]
    review_pct = 100 * reviewed / total if total else 0.0
    review_width = 512 * review_pct / 100
    if values["pending"] or values["unresolved"]:
        exact_label = "denominator open"
        exact_width = 0.0
        exact_detail = f"{values['matches']:,} exact functions · {values['exact_bytes']:,} exact bytes"
        aria_exact = "authored exact denominator open"
    else:
        exact_pct = 100 * values["exact_bytes"] / values["authored_bytes"] if values["authored_bytes"] else 0.0
        exact_label = f"{exact_pct:.2f}%"
        exact_width = 512 * exact_pct / 100
        exact_detail = f"{values['matches']:,} / {values['authored']:,} functions · {values['exact_bytes']:,} / {values['authored_bytes']:,} bytes"
        aria_exact = f"authored {exact_pct:.2f}% exact bytes"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="560" height="176" role="img" aria-label="TH09 reconstruction progress: {aria_exact}, origin review {review_pct:.2f}%">
  <rect width="560" height="176" rx="8" fill="#1f2335"/>
  <text x="24" y="28" fill="#f4f4f5" font-family="sans-serif" font-size="16" font-weight="600">TH09 reconstruction progress</text>
  <text x="24" y="52" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Authored exact</text>
  <text x="536" y="52" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{exact_label}</text>
  <rect x="24" y="60" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="60" width="{exact_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="89" fill="#c8cad2" font-family="sans-serif" font-size="12">{exact_detail}</text>
  <text x="24" y="116" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Origin/boundary reviewed</text>
  <text x="536" y="116" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{review_pct:.2f}%</text>
  <rect x="24" y="124" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="124" width="{review_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="153" fill="#c8cad2" font-family="sans-serif" font-size="12">{reviewed:,} / {total:,} candidates · {values['pending']:,} pending · {values['unresolved']:,} unresolved</text>
</svg>
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = measures()
    markdown, svg = render_markdown(values), render_svg(values)
    if args.check:
        stale = []
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != markdown:
            stale.append(str(OUTPUT.relative_to(ROOT)))
        if not SVG.exists() or SVG.read_text(encoding="utf-8") != svg:
            stale.append(str(SVG.relative_to(ROOT)))
        if stale:
            print(f"error: stale generated progress: {', '.join(stale)}")
            return 1
        print("progress artifacts are current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SVG.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(markdown, encoding="utf-8")
    SVG.write_text(svg, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {SVG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
