#pragma once

#include <stddef.h>

// TH09 v1.50a ECL wire protocol recovered from EclManager::RunEcl at
// 0x004086C0.  Identifiers are maintained role names, not claimed original
// symbols.  The twenty UNHANDLED slots all dispatch to the target's common
// default path at 0x0040B410; adjacent-game meanings are deliberately not
// assigned to those inactive TH09 entries.
enum Th09EclOpcode
{
    // Interpreter control, variables, arithmetic, interpolation, and calls.
    TH09_ECL_OPCODE_TERMINATE = 1,
    TH09_ECL_OPCODE_SET_SECONDARY_TIME = 2,
    TH09_ECL_OPCODE_UNHANDLED_03 = 3,
    TH09_ECL_OPCODE_JUMP = 4,
    TH09_ECL_OPCODE_JUMP_DEC = 5,
    TH09_ECL_OPCODE_SET_INT = 6,
    TH09_ECL_OPCODE_SET_FLOAT = 7,
    TH09_ECL_OPCODE_SET_INT_RANDOM_SIGN = 8,
    TH09_ECL_OPCODE_SET_FLOAT_RANDOM_SIGN = 9,
    TH09_ECL_OPCODE_INT_ADD_ASSIGN = 10,
    TH09_ECL_OPCODE_INT_SUBTRACT_ASSIGN = 11,
    TH09_ECL_OPCODE_INT_MULTIPLY_ASSIGN = 12,
    TH09_ECL_OPCODE_INT_DIVIDE_ASSIGN = 13,
    TH09_ECL_OPCODE_INT_MODULO_ASSIGN = 14,
    TH09_ECL_OPCODE_FLOAT_ADD_ASSIGN = 15,
    TH09_ECL_OPCODE_FLOAT_SUBTRACT_ASSIGN = 16,
    TH09_ECL_OPCODE_FLOAT_MULTIPLY_ASSIGN = 17,
    TH09_ECL_OPCODE_FLOAT_DIVIDE_ASSIGN = 18,
    TH09_ECL_OPCODE_FLOAT_MODULO_ASSIGN = 19,
    TH09_ECL_OPCODE_INT_ADD = 20,
    TH09_ECL_OPCODE_INT_SUBTRACT = 21,
    TH09_ECL_OPCODE_INT_MULTIPLY = 22,
    TH09_ECL_OPCODE_INT_DIVIDE = 23,
    TH09_ECL_OPCODE_INT_MODULO = 24,
    TH09_ECL_OPCODE_FLOAT_ADD = 25,
    TH09_ECL_OPCODE_FLOAT_SUBTRACT = 26,
    TH09_ECL_OPCODE_FLOAT_MULTIPLY = 27,
    TH09_ECL_OPCODE_FLOAT_DIVIDE = 28,
    TH09_ECL_OPCODE_FLOAT_MODULO = 29,
    TH09_ECL_OPCODE_INT_INCREMENT = 30,
    TH09_ECL_OPCODE_INT_DECREMENT = 31,
    TH09_ECL_OPCODE_FLOAT_SINE = 32,
    TH09_ECL_OPCODE_FLOAT_COSINE = 33,
    TH09_ECL_OPCODE_POINT_ANGLE = 34,
    TH09_ECL_OPCODE_INTERPOLATE_VALUE = 35,
    TH09_ECL_OPCODE_INSTALL_INTERPOLATION = 36,
    TH09_ECL_OPCODE_NORMALIZE_ANGLE = 37,
    TH09_ECL_OPCODE_POLAR_TO_CARTESIAN = 38,
    TH09_ECL_OPCODE_POINT_DISTANCE = 39,
    TH09_ECL_OPCODE_JUMP_IF_INT_EQUAL = 40,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_EQUAL = 41,
    TH09_ECL_OPCODE_JUMP_IF_INT_NOT_EQUAL = 42,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_NOT_EQUAL = 43,
    TH09_ECL_OPCODE_JUMP_IF_INT_LESS = 44,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_LESS = 45,
    TH09_ECL_OPCODE_JUMP_IF_INT_LESS_EQUAL = 46,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_LESS_EQUAL = 47,
    TH09_ECL_OPCODE_JUMP_IF_INT_GREATER = 48,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_GREATER = 49,
    TH09_ECL_OPCODE_JUMP_IF_INT_GREATER_EQUAL = 50,
    TH09_ECL_OPCODE_JUMP_IF_FLOAT_GREATER_EQUAL = 51,
    TH09_ECL_OPCODE_CALL = 52,
    TH09_ECL_OPCODE_RETURN = 53,

    // Enemy ANM, movement, hitboxes, and interaction state.
    TH09_ECL_OPCODE_SET_MAIN_ANM = 54,
    TH09_ECL_OPCODE_SET_PRIMARY_ANM_SEQUENCE = 55,
    TH09_ECL_OPCODE_SET_PRIMARY_ANM_SCRIPTS = 56,
    TH09_ECL_OPCODE_SET_EXTRA_ANM_SCRIPT = 57,
    TH09_ECL_OPCODE_SET_MAIN_ANM_ALTERNATE = 58,
    TH09_ECL_OPCODE_SET_PRIMARY_ANM_SEQUENCE_ALTERNATE = 59,
    TH09_ECL_OPCODE_SET_PRIMARY_ANM_SCRIPTS_ALTERNATE = 60,
    TH09_ECL_OPCODE_SET_EXTRA_ANM_SCRIPT_ALTERNATE = 61,
    TH09_ECL_OPCODE_PLAY_SPECIAL_ANM = 62,
    TH09_ECL_OPCODE_SET_POSITION = 63,
    TH09_ECL_OPCODE_MOVE_TO = 64,
    TH09_ECL_OPCODE_SET_DIRECTION_AND_SPEED = 65,
    TH09_ECL_OPCODE_MOVE_IN_DIRECTION = 66,
    TH09_ECL_OPCODE_MOVE_RANDOM_IN_BOUNDS = 67,
    TH09_ECL_OPCODE_SET_AIMED_DIRECTION_AND_SPEED = 68,
    TH09_ECL_OPCODE_MOVE_IN_AIMED_DIRECTION = 69,
    TH09_ECL_OPCODE_SET_ANGULAR_VELOCITY = 70,
    TH09_ECL_OPCODE_SET_ACCELERATION = 71,
    TH09_ECL_OPCODE_ORBIT_AROUND_POINT = 72,
    TH09_ECL_OPCODE_ORBIT_AROUND_CURRENT_POSITION = 73,
    TH09_ECL_OPCODE_SET_ORBIT_VELOCITIES = 74,
    TH09_ECL_OPCODE_SET_MOVEMENT_BOUNDS = 75,
    TH09_ECL_OPCODE_DISABLE_MOVEMENT_BOUNDS = 76,
    TH09_ECL_OPCODE_SET_HITBOX = 77,
    TH09_ECL_OPCODE_SET_SECONDARY_HITBOX = 78,
    TH09_ECL_OPCODE_SET_INTERACTION_FLAGS = 79,
    TH09_ECL_OPCODE_DISABLE_INTERACTION_FLAGS = 80,
    TH09_ECL_OPCODE_ENABLE_INTERACTION_FLAGS = 81,
    TH09_ECL_OPCODE_SET_MINIMUM_PLAYER_DISTANCE = 82,
    TH09_ECL_OPCODE_UNHANDLED_53 = 83,
    TH09_ECL_OPCODE_UNHANDLED_54 = 84,
    TH09_ECL_OPCODE_UNHANDLED_55 = 85,

    // Remote contexts and enemy spawning.
    TH09_ECL_OPCODE_SET_REMOTE_INT = 86,
    TH09_ECL_OPCODE_SET_REMOTE_FLOAT = 87,
    TH09_ECL_OPCODE_CALL_REMOTE = 88,
    TH09_ECL_OPCODE_SCHEDULE_REMOTE_SUBROUTINE = 89,
    TH09_ECL_OPCODE_UNHANDLED_5A = 90,
    TH09_ECL_OPCODE_UNHANDLED_5B = 91,
    TH09_ECL_OPCODE_UNHANDLED_5C = 92,
    TH09_ECL_OPCODE_SPAWN_ENEMY_AT_POSITION = 93,
    TH09_ECL_OPCODE_SPAWN_ENEMY_RELATIVE = 94,
    TH09_ECL_OPCODE_KILL_ALL_NON_BOSS_ENEMIES = 95,

    // Bullet and laser pattern control.
    TH09_ECL_OPCODE_SHOOT_FAN_AIMED = 96,
    TH09_ECL_OPCODE_SHOOT_FAN = 97,
    TH09_ECL_OPCODE_SHOOT_CIRCLE_AIMED = 98,
    TH09_ECL_OPCODE_SHOOT_CIRCLE = 99,
    TH09_ECL_OPCODE_SHOOT_OFFSET_CIRCLE_AIMED = 100,
    TH09_ECL_OPCODE_SHOOT_OFFSET_CIRCLE = 101,
    TH09_ECL_OPCODE_SHOOT_RANDOM_ANGLE = 102,
    TH09_ECL_OPCODE_SHOOT_RANDOM_SPEED = 103,
    TH09_ECL_OPCODE_SHOOT_RANDOM = 104,
    TH09_ECL_OPCODE_SET_SHOOT_INTERVAL = 105,
    TH09_ECL_OPCODE_SET_SHOOT_INTERVAL_DELAYED = 106,
    TH09_ECL_OPCODE_ENABLE_DEFERRED_SHOOTING = 107,
    TH09_ECL_OPCODE_DISABLE_DEFERRED_SHOOTING = 108,
    TH09_ECL_OPCODE_SHOOT_NOW = 109,
    TH09_ECL_OPCODE_SET_SHOOT_OFFSET = 110,
    TH09_ECL_OPCODE_SET_BULLET_TRANSFORM = 111,
    TH09_ECL_OPCODE_CLEAR_BULLETS_FOR_TRANSITION = 112,
    TH09_ECL_OPCODE_SET_BULLET_SOUNDS = 113,
    TH09_ECL_OPCODE_CREATE_LASER = 114,
    TH09_ECL_OPCODE_CREATE_LASER_AIMED = 115,
    TH09_ECL_OPCODE_SELECT_LASER_SLOT = 116,
    TH09_ECL_OPCODE_ROTATE_LASER = 117,
    TH09_ECL_OPCODE_AIM_LASER_AT_PLAYER = 118,
    TH09_ECL_OPCODE_SET_LASER_POSITION = 119,
    TH09_ECL_OPCODE_TEST_LASER_ACTIVE = 120,
    TH09_ECL_OPCODE_CANCEL_LASER = 121,
    TH09_ECL_OPCODE_UNHANDLED_7A = 122,
    TH09_ECL_OPCODE_UNHANDLED_7B = 123,

    // Sound, boss/death lifecycle, callbacks, effects, and item state.
    TH09_ECL_OPCODE_PLAY_POSITIONED_SOUND = 124,
    TH09_ECL_OPCODE_CALL_SUBROUTINE_SLOT = 125,
    TH09_ECL_OPCODE_SET_SUBROUTINE_SLOT = 126,
    TH09_ECL_OPCODE_SET_BOSS = 127,
    TH09_ECL_OPCODE_ATTACH_SPELL_EFFECT = 128,
    TH09_ECL_OPCODE_SET_DEATH_MODE = 129,
    TH09_ECL_OPCODE_SET_DEATH_CALLBACK = 130,
    TH09_ECL_OPCODE_SET_LIFE = 131,
    TH09_ECL_OPCODE_SET_BOSS_TIMER = 132,
    TH09_ECL_OPCODE_SET_LIFE_CALLBACK = 133,
    TH09_ECL_OPCODE_SET_TIMER_CALLBACK = 134,
    TH09_ECL_OPCODE_SET_CHILD_ECL = 135,
    TH09_ECL_OPCODE_CALL_EX_INSTRUCTION = 136,
    TH09_ECL_OPCODE_SET_REPEATING_EX_INSTRUCTION = 137,
    TH09_ECL_OPCODE_SET_DEATH_ANM_SCRIPTS = 138,
    TH09_ECL_OPCODE_SPAWN_EFFECT = 139,
    TH09_ECL_OPCODE_SPAWN_EFFECT_WITH_VELOCITY = 140,
    TH09_ECL_OPCODE_UNHANDLED_8D = 141,
    TH09_ECL_OPCODE_UNHANDLED_8E = 142,
    TH09_ECL_OPCODE_SET_ITEM_DROP_TYPE = 143,
    TH09_ECL_OPCODE_SET_ITEM_DROP_COUNTS = 144,
    TH09_ECL_OPCODE_SET_ANM_ROTATION_ENABLED = 145,
    TH09_ECL_OPCODE_ADD_TIME = 146,
    TH09_ECL_OPCODE_SET_BACKGROUND_SCRIPT_LABEL = 147,
    TH09_ECL_OPCODE_SET_BOSS_LIFE_MARKER_COUNT = 148,
    TH09_ECL_OPCODE_INTERRUPT_MAIN_ANM = 149,
    TH09_ECL_OPCODE_INTERRUPT_SECONDARY_ANM = 150,
    TH09_ECL_OPCODE_SET_CALL_STACK_DISABLED = 151,
    TH09_ECL_OPCODE_SET_BULLET_RANK_INFLUENCE = 152,
    TH09_ECL_OPCODE_RESET_BOSS_TIMER_CALLBACK = 153,
    TH09_ECL_OPCODE_CLEAR_LASER_SLOTS = 154,
    TH09_ECL_OPCODE_SET_TIMEOUT_SPELL = 155,
    TH09_ECL_OPCODE_SET_SPECIAL_INTERACTION = 156,
    TH09_ECL_OPCODE_SET_TRAIL = 157,
    TH09_ECL_OPCODE_UNHANDLED_9E = 158,

    // Late manager, bullet cleanup, laser, timing, and side-state protocol.
    TH09_ECL_OPCODE_SET_DRAW_GROUP = 159,
    TH09_ECL_OPCODE_SET_DAMAGE_REDUCTION_TIMER = 160,
    TH09_ECL_OPCODE_REMOVE_BULLETS_IN_RADIUS = 161,
    TH09_ECL_OPCODE_REMOVE_ALL_BULLETS = 162,
    TH09_ECL_OPCODE_SET_MANAGER_PROTOCOL_VALUE = 163,
    TH09_ECL_OPCODE_UNHANDLED_A4 = 164,
    TH09_ECL_OPCODE_SET_MAIN_ANM_ROTATION = 165,
    TH09_ECL_OPCODE_POLAR_TO_CARTESIAN_ALT = 166,
    TH09_ECL_OPCODE_SET_LASER_ANGLE = 167,
    TH09_ECL_OPCODE_UNHANDLED_A8 = 168,
    TH09_ECL_OPCODE_RANDOM_HORIZONTAL_ANGLE = 169,
    TH09_ECL_OPCODE_SET_LASER_START_CAP_HIDDEN = 170,
    TH09_ECL_OPCODE_SET_LASER_START_LENGTH = 171,
    TH09_ECL_OPCODE_SET_LASER_OFFSETS = 172,
    TH09_ECL_OPCODE_SET_TIMER_PAUSED = 173,
    TH09_ECL_OPCODE_UNHANDLED_AE = 174,
    TH09_ECL_OPCODE_SET_TIMELINE_SPAWNS_SUPPRESSED = 175,
    TH09_ECL_OPCODE_UNHANDLED_B0 = 176,
    TH09_ECL_OPCODE_SET_PHASE_STARTING_LIFE = 177,
    TH09_ECL_OPCODE_MOVE_RANDOM_BIASED = 178,
    TH09_ECL_OPCODE_UNHANDLED_B3 = 179,
    TH09_ECL_OPCODE_UNHANDLED_B4 = 180,
    TH09_ECL_OPCODE_UNHANDLED_B5 = 181,
    TH09_ECL_OPCODE_SET_EXTRA_ANM_FIXED_OFFSET = 182,
    TH09_ECL_OPCODE_SET_NO_DAMAGE_DURING_STOP = 183,
    TH09_ECL_OPCODE_UNHANDLED_B8 = 184,

    // TH09-only tail relative to the committed TH08 family.
    TH09_ECL_OPCODE_SET_SIDE_CATEGORY = 185,
    TH09_ECL_OPCODE_TRIGGER_SIDE_OWNER_STATE = 186,
    TH09_ECL_OPCODE_SET_SECONDARY_FLAG_4000 = 187
};

enum
{
    TH09_ECL_OPCODE_MIN = 1,
    TH09_ECL_OPCODE_MAX = 187,
    TH09_ECL_OPCODE_ACTIVE_COUNT = 167,
    TH09_ECL_OPCODE_DEFAULT_COUNT = 20
};

// Fixed portion of every variable-length ECL instruction.  Argument bytes
// begin immediately at +0x0C; nextOffset advances to the next instruction.
struct Th09EclRawInstructionHeaderView
{
    int time00;
    short opcode04;
    unsigned short nextOffset06;
    unsigned char unknown08;
    unsigned char difficultyMask09;
    unsigned short parameterMask0A;
};

typedef char Th09EclRawInstructionHeaderSizeIs0C[
    (sizeof(Th09EclRawInstructionHeaderView) == 0x0C) ? 1 : -1];
typedef char Th09EclOpcodeAt04[
    (offsetof(Th09EclRawInstructionHeaderView, opcode04) == 0x04) ? 1 : -1];
typedef char Th09EclNextOffsetAt06[
    (offsetof(Th09EclRawInstructionHeaderView, nextOffset06) == 0x06) ? 1 : -1];
typedef char Th09EclDifficultyMaskAt09[
    (offsetof(Th09EclRawInstructionHeaderView, difficultyMask09) == 0x09) ? 1 : -1];
typedef char Th09EclParameterMaskAt0A[
    (offsetof(Th09EclRawInstructionHeaderView, parameterMask0A) == 0x0A) ? 1 : -1];

struct Th09EclTimerStorageView
{
    operator int();
    operator float();
    unsigned int operator==(int value);
    unsigned int operator>=(int value);
    void operator=(int value);
    void SetCurrent(int value);
    void AddCurrent(int value);
    void operator+=(int value);
    void operator+=(float value);
    void operator--(int value);

    int previous00;
    float subFrame04;
    int current08;
};
typedef char Th09EclTimerStorageSizeIs0C[
    (sizeof(Th09EclTimerStorageView) == 0x0C) ? 1 : -1];

struct Th09EclInterpolationSlotView
{
    void *callback00;
    Th09EclTimerStorageView timer04;
    int duration10;
    int unknown14;
    int easing18;
    unsigned char unknown1C[0x10];
    float affectedVariable2C;
};
typedef char Th09EclInterpolationSlotSizeIs30[
    (sizeof(Th09EclInterpolationSlotView) == 0x30) ? 1 : -1];
typedef char Th09EclInterpolationEasingAt18[
    (offsetof(Th09EclInterpolationSlotView, easing18) == 0x18) ? 1 : -1];
typedef char Th09EclInterpolationVariableAt2C[
    (offsetof(Th09EclInterpolationSlotView, affectedVariable2C) == 0x2C) ? 1 : -1];

// RunEcl copies this complete 0x22C context into a 16-entry main call stack.
// The callback and interpolation role names describe target-observed use.
struct Th09EclContextView
{
    unsigned char unknown000[0x04];
    Th09EclRawInstructionHeaderView *currentInstruction004;
    Th09EclTimerStorageView time008;
    void *perFrameCallback014;
    void *perFrameInstruction018;
    unsigned char unknown01C[0x94 - 0x1C];
    Th09EclTimerStorageView secondaryTime094;
    Th09EclInterpolationSlotView interpolationSlots0A0[8];
    unsigned char unknown220[0x04];
    int contextOrdinal224;
    short subroutineId228;
    unsigned char unknown22A[0x02];
};
typedef char Th09EclContextSizeIs22C[
    (sizeof(Th09EclContextView) == 0x22C) ? 1 : -1];
typedef char Th09EclContextCurrentInstructionAt004[
    (offsetof(Th09EclContextView, currentInstruction004) == 0x04) ? 1 : -1];
typedef char Th09EclContextSecondaryTimeAt094[
    (offsetof(Th09EclContextView, secondaryTime094) == 0x94) ? 1 : -1];
typedef char Th09EclContextInterpolationsAt0A0[
    (offsetof(Th09EclContextView, interpolationSlots0A0) == 0xA0) ? 1 : -1];
typedef char Th09EclContextOrdinalAt224[
    (offsetof(Th09EclContextView, contextOrdinal224) == 0x224) ? 1 : -1];
typedef char Th09EclContextSubroutineAt228[
    (offsetof(Th09EclContextView, subroutineId228) == 0x228) ? 1 : -1];

enum Th09EclEnemyRuntimeOffset
{
    TH09_ECL_ENEMY_MAIN_CONTEXT = 0x07F4,
    TH09_ECL_ENEMY_MAIN_CALL_STACK = 0x0A20,
    TH09_ECL_ENEMY_ACTIVE_CONTEXT = 0x2CE0,
    TH09_ECL_ENEMY_ACTIVE_CALL_STACK = 0x2CE4,
    TH09_ECL_ENEMY_MAIN_CALL_DEPTH = 0x2D28,
    TH09_ECL_ENEMY_ACTIVE_CALL_DEPTH = 0x2D2A,
    TH09_ECL_ENEMY_PENDING_SUB_ID = 0x2D70,
    TH09_ECL_ENEMY_DIFFICULTY_OVERRIDE = 0x3388,
    TH09_ECL_ENEMY_CHILD_BLOCKS = 0x33D8,
    TH09_ECL_MAIN_CALL_STACK_CAPACITY = 16,
    TH09_ECL_INTERPOLATION_SLOT_COUNT = 8,
    TH09_ECL_CHILD_CONTEXT_COUNT = 4
};

typedef char Th09EclMainStackEndsAtActiveContext[
    (TH09_ECL_ENEMY_MAIN_CALL_STACK +
         sizeof(Th09EclContextView) * TH09_ECL_MAIN_CALL_STACK_CAPACITY ==
     TH09_ECL_ENEMY_ACTIVE_CONTEXT) ? 1 : -1];
